export const SET_APP_THEME = 'SET_APP_THEME';
export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';

// AUTH
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const USER_SESSION_CHANGE_STATE = 'USER_SESSION_CHANGE_STATE';
export const SET_USER = 'SET_USER';
export const CREATE_USER = 'CREATE_USER';

// LOGOUT 
export const LOGOUT = 'LOGOUT'